baseURL = 'https://nherve.dev/'

locale = "en"
defaultContentLanguage = "en"
hasCJKLanguage = false
languageCode = 'en-US'

title = "N(H)erve'd powered chronicles"

theme = "DoIt"

enableRobotsTXT= true

[params]
  version = "0.4.X"
  fingerprint = "sha256"
  enablePWA = false

  # Author config
  [params.author]
    name = "Hervé-M"
    email = "https://mailhide.io/e/Hz13VXLP"
    gravatarEmail = "herve.matysiak@viacesi.fr"

  # Social config about the author
  [params.social]
    GitHub = "Herve-M"
    Linkedin = "hervematysiak"
    Twitter = "HerveMATHY"
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    ORCID = ""
    Liberapay = ""
    Ko-Fi = ""
    BuyMeACoffee = ""
    Linktree = ""
    QQ = ""
    QQGroup = ""
    Email = ""
    RSS = true
    [params.social.Mastodon]
      id = "@Herve_M"
      prefix = "https://fosstodon.org/"

  [params.image]
    # cache remote images for better optimisations
    cacheRemote = false
    # Image resizing and optimisation
    optimise = false

  [params.home]
    [params.home.profile]
      enable = true
      gravatarEmail = "herve.matysiak@viacesi.fr"
      avatarURL = ""
      avatarLinkURL = ""
      title = ""
      subtitle = ""
      typeit = false
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 7

  # Header config
  [params.header]
    # theme change mode ("switch", "select")
    themeChangeMode = "switch"
    [params.header.title]
      logo = ""
      name = "N(H)erve'd powered chronicles"
      pre = ""
      post = ""
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    custom = ''
    hugo = true
    # DoIt NEW | 0.2.14 Hosted on (HTML format is supported)
    # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreferrer">GitHub Pages</a>
    hostedOn = '<a title="Cloudflare Pages" href="https://pages.cloudflare.com/" target="_blank" rel="noopener noreferrer">Cloudflare Pages</a>'
    copyright = true
    author = true
    since = 2019
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  
  [params.page]
    [params.page.instantpage]
      enable = false

    [params.page.outdatedArticleReminder]
      enable = true
      reminder = 180
      warning = 365

    [params.page.toc]
      enable = true
      keepStatic = false
      auto = false

    [params.page.share]    
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = true
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
      Mastodon = true

    [params.page.comment]
      enable = false
  
  [params.cdn]
    data = ""

  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false

  [params.analytics]
    enable = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  series = "series"