baseURL = 'https://nherve.dev/'
languageCode = 'en-us'
title = "N(H)erve'd powered chronicles"

theme = "FeelIt"

enableRobotsTXT= true

[author]
    name = "Hervé-M"
    email= "https://mailhide.io/e/Hz13VXLP"
    link = ""

[params]
  version = "1.0.X"
  [params.page.share]    
    enable = true
    Twitter = true
    Facebook = false
    Linkedin = true
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = true
    Reddit = true
    VK = false
    Buffer = false
    Xing = false
    Line = false
    Instapaper = false
    Pocket = false
    Digg = false
    Stumbleupon = false
    Flipboard = false
    Weibo = false
    Renren = false
    Myspace = false
    Blogger = false
    Baidu = false
    Odnoklassniki = false
    Evernote = false
    Skype = false
    Trello = false
    Mix = false
    [params.page.comment]
      enable = false
  [params.social]
    GitHub = "https://github.com/Herve-M/"
    Linkedin = "https://www.linkedin.com/in/hervematysiak"
    Twitter = "https://twitter.com/HerveMATHY"
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Email = ""
    Resume = "" 
    xda = ""
    RSS = true
    [params.social.Mastodon]
      id = "@Herve_M"
      prefix = "https://fosstodon.org/"
    
  [params.cdn]
    data = "jsdelivr.yml"

  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false

[params.home.posts]
  imagePreview = true

[params.analytics]
  enable = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    [languages.en.params]
       description = "Welcome to N(H)erve'd Powered Chronicles—a quirky blend of code, creativity, and (maybe too much) caffeine. Dive into a world where tech meets humor, and every line of code comes with a side of adventure… or possibly disappointment!"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "Posts"
        url = "/posts/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3