baseURL = 'https://beta.hervematysiak.org/'
title = "[BETA] N(H)erve'd powered chronicles"

[params.analytics]
    enable = true
    [params.analytics.plausible]
      dataDomain = "beta.nherve.dev"

[params.page]
  cdnfontawesome = true
  [params.page.comment]
    enable = true
    [params.page.comment.giscus]
    enable = true
    repo = "Herve-M/blog"
    repoId = "MDEwOlJlcG9zaXRvcnk4MDkzMzQyNg=="
    category = "[BETA] Annoucements"
    categoryId = "DIC_kwDOBNLyMs4CQ92X"