baseURL = 'https://beta.nherve.dev'
title = "[BETA] N(H)erve'd powered chronicles"

[params]
  [params.cdn]
    data = "jsdelivr.yml"

  [params.analytics]
    enable = true
    [params.analytics.plausible]
      data_domain = "beta.nherve.dev"
      src = "https://statistics.nherve.dev/js/pa-98XIcVjbN6mNRzymd3all.js"

  [params.page]
    [params.page.comment]
      enable = true
      [params.page.comment.giscus]
        enable = true
        dataRepo = "Herve-M/blog"
        dataRepoId = "MDEwOlJlcG9zaXRvcnk4MDkzMzQyNg=="
        dataCategory = "[BETA] Annoucements"
        dataCategoryId = "DIC_kwDOBNLyMs4CQ92X"