dist: bionic
sudo: false
language: go
go:
- stable

addons:
  ssh_known_hosts:
  - beta.hervematysiak.eu
  - hervematysiak.eu

install:
  - go get github.com/spf13/hugo
  - npm install html-minifier -g

before_deploy:
  - ./.travis/before_deploy.sh

script:
  - ./.travis/build.sh

deploy:
  provider: script
  script: ./.travis/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true

notifications:
    email:
        on_success: never
        on_failure: change
