name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: git lfs pull

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --environment production --buildExpired --minify
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Copy AzureStaticAppConfig
        run: mv ./config/production/staticwebapp.config.json ./public/staticwebapp.config.json
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Build (staging)
        run: hugo --environment staging --buildDrafts --buildExpired --buildFuture
        if: ${{ github.ref == 'refs/heads/develop' }}

      - name: Copy AzureStaticAppConfig (staging)
        run: mv ./config/staging/staticwebapp.config.json ./public/staticwebapp.config.json
        if: ${{ github.ref == 'refs/heads/develop' }}

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_SMOKE_0C4BB6103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/public" 
          api_location: "/api" 
          output_location: "public"
          skip_app_build: true
          production_branch: "master"

      - name: Deploy (staging)
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV_BLOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/public" 
          api_location: "/api" 
          output_location: "public"
          skip_app_build: true
          production_branch: "develop"